- name: Create backend .env
  working-directory: fs-graphql/library-backend
  run: |
    echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" > .env

- name: Verify .env
  working-directory: fs-graphql/library-backend
  run: |
    pwd
    ls -la
    cat .env
